version: '3.7'
services:
  db:
    image: postgres:latest
    container_name: db_app
    command: -p 5454
    expose:
      - 5454
    env_file:
      - .env-deploy

  redis:
    image: redis:5
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  app:
    build:
      context: .
    env_file:
      - .env-deploy
    container_name: drf_app
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8001:8000
    depends_on:
      - db
      - redis